### ISSUE TITLE
gradle setupDecompWorkspace fails

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeForge#484]
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\JBYoshi\git\SpongeForge\SpongeCommon\SpongeAPI\build.gradle' line: 106

* What went wrong:
A problem occurred evaluating project ':SpongeCommon:SpongeAPI'.
> org/spongepowered/gradle/TaskSortClassMembers

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':SpongeCommon:SpongeAPI'.
        at (skipped for brevity)
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/gradle/TaskSortClassMembers
        at build_d6q6y4vy0b820jf89n19nf6we.run(C:\Users\JBYoshi\git\SpongeForge\SpongeCommon\SpongeAPI\build.gradle:106)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
        ... 98 more


BUILD FAILED
```

**Comment by Minecrell** [comment]
Probably similar to the task in SpongeCommon, caused by https://github.com/SpongePowered/SpongeAPI/commit/bf798dc7fdd7a54748fe413890def8e94390c1bf
I'd guess Gradle only takes a look at the root project's buildSrc...

**Comment by JBYoshi** [comment]
Running gradle on SpongeAPI works. Maybe it just checks the current directory?

**Comment by mcsnetworks** [comment]
Are you using: gradlew setupDecompWorkspace --refresh-dependencies 

?

**Comment by JBYoshi** [comment]
It was fixed with the addition of SpongeGradle.
